//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gifer {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gifer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fand (Quality).
        /// </summary>
        internal static string EN_Settings_RenderingModeFant {
            get {
                return ResourceManager.GetString("EN_Settings_RenderingModeFant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rendering:.
        /// </summary>
        internal static string EN_Settings_RenderingModeLabel {
            get {
                return ResourceManager.GetString("EN_Settings_RenderingModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Linear (Fast).
        /// </summary>
        internal static string EN_Settings_RenderingModeLinear {
            get {
                return ResourceManager.GetString("EN_Settings_RenderingModeLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nearest neighbot (Raw pixels).
        /// </summary>
        internal static string EN_Settings_RenderingModeNearestNeighbor {
            get {
                return ResourceManager.GetString("EN_Settings_RenderingModeNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fant (Качественное).
        /// </summary>
        internal static string RU_Settings_RenderingModeFant {
            get {
                return ResourceManager.GetString("RU_Settings_RenderingModeFant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сглаживание:.
        /// </summary>
        internal static string RU_Settings_RenderingModeLabel {
            get {
                return ResourceManager.GetString("RU_Settings_RenderingModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Линейное (Быстрое).
        /// </summary>
        internal static string RU_Settings_RenderingModeLinear {
            get {
                return ResourceManager.GetString("RU_Settings_RenderingModeLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ближайший сосед (Оригинальные пиксели).
        /// </summary>
        internal static string RU_Settings_RenderingModeNearestNeighbor {
            get {
                return ResourceManager.GetString("RU_Settings_RenderingModeNearestNeighbor", resourceCulture);
            }
        }
    }
}
